<!--Order status field -->
<div class="fieldset admin__field">
    <label for="order_status" class="admin__field-label">
        <span><?= $block->escapeHtml(__('Order status :')) ?></span>                    
    </label> 
    <span><?= $block->getSelectedOrderStatus() ?></span>
</div>

<!--Ordered Products Types field -->
<div class="fieldset admin__field">
    <label for="product_types" class="admin__field-label">
        <span><?= $block->escapeHtml(__('Ordered Products Types :')) ?></span>                    
    </label> 
    <span><?= $block->getSelectedProductsTypes() ?></span>
</div>

<!--Button Export Orders -->
<div class="fieldset admin__field">
    <form id="export_orders"
          class="admin__fieldset"
          action="<?= $block->escapeUrl($block->getUrl($block->getExportActionPath())) ?>"
          method="post">        
              <?= $block->getBlockHtml('formkey') ?>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Export Orders')) ?>"
                        class="action submit primary">
                    <span><?= $block->escapeHtml(__('Export Orders')) ?></span>
                </button>
            </div>
        </div>     
    </form>        
</div>