<!--Orders status field -->
<div class="fieldset admin__field">
    <label for="product_types" class="admin__field-label">
        <span><?= $block->escapeHtml(__('Order status :')) ?></span>                    
    </label>
    <div style="padding-left: 20px;">
        <?php foreach ($block->getSelectedOrderStatus() as $orderStaus): ?>   
            <ul>
                <li><?= \ucfirst($orderStaus) ?></li>
            </ul>
        <?php endforeach; ?>
    </div>
</div>

<!--Ordered Products Types field -->
<div class="fieldset admin__field">
    <label for="product_types" class="admin__field-label">
        <span><?= $block->escapeHtml(__('Ordered Products Types :')) ?></span>                    
    </label>
    <div style="padding-left: 20px;">
        <?php foreach ($block->getSelectedProductsTypes() as $productType): ?>   
            <ul>
                <li><?= \ucfirst($productType)  ?></li>
            </ul>
        <?php endforeach; ?>
    </div>     
</div>

<!--Order attributes -->
<div class="fieldset admin__field">
    <label for="product_types" class="admin__field-label">
        <span><?= $block->escapeHtml(__('Order Attributes :')) ?></span>                    
    </label>
    <div style="padding-left: 20px;">
        <?php foreach ($block->getSelectedOrderAttributesLabels() as $attributeLabel): ?>   
            <ul>
                <li><?= $attributeLabel  ?></li>
            </ul>
        <?php endforeach; ?>
    </div>     
</div>

<!--Button Change Settins -->
<div class="fieldset admin__field">
    <form id="export_orders"
          class="admin__fieldset"
          action="<?= $block->escapeUrl($block->getUrl($block->getConfigsPath())) ?>"
          method="post">        
              <?= $block->getBlockHtml('formkey') ?>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Change Settins')) ?>"
                        class="action submit primary">
                    <span><?= $block->escapeHtml(__('Change Settins')) ?></span>
                </button>
            </div>
        </div>     
    </form>        
</div>


<!--Button Export Orders -->
<div class="fieldset admin__field">
    <form id="export_orders"
          class="admin__fieldset"
          action="<?= $block->escapeUrl($block->getUrl($block->getExportActionPath())) ?>"
          method="post">        
              <?= $block->getBlockHtml('formkey') ?>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Export Orders')) ?>"
                        class="action submit primary">
                    <span><?= $block->escapeHtml(__('Export Orders')) ?></span>
                </button>
            </div>
        </div>     
    </form>        
</div>