<?php
echo "<b>Raw data from csv file:</b></br></br>";
$rawCsvData = $block->getRawCsvData();
print_r($rawCsvData );
echo "<br></br>";
echo "<b>Validated data from csv file:</b></br></br>";
print_r($block->getValidatedCsvData($rawCsvData));
echo "<br><br>";
echo "<b>Processed data from csv file:</b></br></br>";
print_r($block->getProcessedCsvData(($rawCsvData)));
echo "<br><br>";
//echo "<b>Log messages:</b></br></br>";
//echo $block->csvLogger();
echo "<b>List of sources:</b></br></br>";
$sourceList = $block->getSourceList();
$source_codes = [];
foreach ($sourceList as $source) {
    $source_codes[] = $source->getData()['source_code'];
}
print_r($source_codes);
echo "<br><br>";
echo "<b>Columns names:</b></br></br>";
print_r($block->getCsvHeader(BP. DS .'pub' . DS .'media'. DS . 'import'. DS .'local_import.csv'));
echo "<br><br>";
print_r($block->getRowLength(BP. DS .'pub' . DS .'media'. DS . 'import'. DS .'local_import.csv'));
echo "<br><br>";
print_r($block->getDirectCsvRawData(BP. DS .'pub' . DS .'media'. DS . 'import'. DS .'local_import.csv'));




